QUALTRICS_TEST_OBJECTS = {
    'unittest-contact-list-1': {
        'id': 'ML_6ifLPwSfjagoQ3H',
    },
    'unittest-survey-1': {
        'id': 'SV_2avH1JdVZa8eEAd',
        'export_tags': [
            'StartDate',
            'EndDate',
            'Status',
            'IPAddress',
            'Progress',
            'Duration (in seconds)',
            'Finished',
            'RecordedDate',
            'LocationLatitude',
            'LocationLongitude',
            'DistributionChannel',
            'UserLanguage',
            'Q12_1',
            'Q12_2',
            'Q12_3',
            'Q12_4',
            'Q12_5',
            'Q12_6',
            'Q12_7',
            'Q12_8',
            'Q1',
            'Q1COM',
            'Q2',
            'Q2COM',
            'Q3',
            'Q12',
            'Q12_8_TEXT',
            'Q14',
            'Q14_12_TEXT',
            'Q12_DO',
            'Q1_DO',
            'Q2_DO',
            'Q3_DO',
            'Q4_DO',
            'Q14_DO',
            'Q1COM_DO',
            'Q4COM_DO',
            'RecipientEmail',
            'Q3COM',
            'Q2COM_DO',
            'RecipientLastName',
            'RecipientFirstName',
            'ExternalReference',
            'Q4',
            'Q4COM',
            'Q3COM_DO',
        ],
        'response_1_id': 'R_1BziZVeffoDpTQl',
        'response_2_id': 'R_0d1ampzLtZpZRjX',
    },
}