name: Feature pipeline

on:
  push:
    branches:
      - 'cicd-*'
  pull_request:
    branches:
      - 'master'


env:
  PIPELINE_USER_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  PIPELINE_USER_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  EPSAGON_TOKEN: ${{ secrets.EPSAGON_TOKEN }}
  SAM_TEMPLATE: template.yaml
  AWS_REGION: eu-west-1
  STACK_NAME: thiscovery-crm


jobs:
  deploy-testing:
    name: Deploy to test env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure testing environment
        uses: THIS-Labs/actions-configure-test-env@v0.15
        with:
          afs25_account: ${{ secrets.AFS25_AWS_ACCOUNT }}
          sem86_account: ${{ secrets.SEM86_AWS_ACCOUNT }}
          amp205_account: ${{ secrets.AMP205_AWS_ACCOUNT }}

      - name: Build
        uses: THIS-Labs/actions-build-stack@v0.3

      - name: Package
        uses: THIS-Labs/actions-package-stack@v0.4
        with:
          from_env: ${{ env.AWS_TEST_ENV }}
          to_env: ${{ env.AWS_TEST_ENV }}
          deployment_role: ${{ env.TESTING_ACCOUNT_DEPLOYMENT_ROLE }}
          artifacts_bucket: ${{ env.ARTIFACTS_BUCKET }}

      - name: Execute thiscovery deployment via cli
        run: |
          thiscovery deploy ${{ env.STACK_NAME }}

  test:
    name: Test on AWS
    needs: [ deploy-testing ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Configure testing environment
        uses: THIS-Labs/actions-configure-test-env@v0.15
        with:
          afs25_account: ${{ secrets.AFS25_AWS_ACCOUNT }}
          sem86_account: ${{ secrets.SEM86_AWS_ACCOUNT }}
          amp205_account: ${{ secrets.AMP205_AWS_ACCOUNT }}

      - name: Install dependencies
        shell: bash
        run: |
          pip install -r requirements.txt

      - name: Assume the testing role in testing account
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ env.PIPELINE_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.TESTING_ACCOUNT_TEST_ROLE }}
          role-session-name: ${{ env.STACK_NAME }}-testing
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Run tests
        uses: THIS-Labs/actions-run-tests@v0.1
